const translations = {
  en: {
    welcome: 'Welcome',
    welcome_to_gly: 'Welcome to GLY',
    username: 'Username',
    email: 'Email',
    password: 'Password',
    confirm_password: 'Confirm Password',
    payment_password: 'Payment Password',
    invite_code_required: 'Invitation Code (required)',
    register: 'Register',
    have_account: 'Already have an account?',
    login_now: 'Login now!',
    validation_required: 'All fields are required',
    validation_password_match: 'Passwords do not match',
    validation_password_length: 'Password must be at least 6 characters',
    validation_payment_password_length: 'Payment password must be at least 6 characters',
    error_username_exists: 'Username already exists',
    error_invalid_invite: 'Invalid invitation code',
    server_error: 'Server error, please try again',
    registering: 'Registering...',
    registration_success: 'Registration successful!',
    login: 'Login',
    no_account: 'Don\'t have an account?',
    register_now: 'Register now!',
    database_error: 'Database error',
    user_not_found: 'User not found',
    invalid_credentials: 'Invalid credentials',
    login_error: 'Login error',
    login_success: 'Login successful!',
    loading: 'Loading...',
    auto_quantification: 'AUTO QUANTIFICATION',
    vip_levels: 'VIP Levels',
    vip_description_1: 'VIP 1: Basic level with 2.2% daily return',
    vip_description_2: 'VIP 2: 2.8% daily return',
    vip_description_3: 'VIP 3: 3.5% daily return',
    vip_description_4: 'VIP 4: 4.0% daily return',
    vip_description_5: 'VIP 5: 5.0% daily return',
    vip_description_6: 'VIP 6: 6.0% daily return',
    daily_percent: 'Daily Percent',
    deposit_range: 'Deposit Range',
    signals_count: 'Signals',
    referrals_required: 'Referrals Required',
    unlocked: 'Unlocked',
    locked: 'Locked',
    id: 'ID',
    copy_id: 'Copy ID',
    balance: 'Balance',
    utc_calendar: 'UTC Calendar',
    settings: 'Settings',
    withdrawal_address: 'Withdrawal Address',
    transaction_password: 'Transaction Password',
    customer_service: 'Customer Service',
    language: 'Language',
    change_password: 'Change Password',
    logout: 'Logout',
    set_withdrawal_address: 'Set Withdrawal Address',
    select_network: 'Select Network',
    usdt_wallet_address: 'USDT Wallet Address',
    enter_wallet_address: 'Enter your wallet address',
    save: 'Save',
    cancel: 'Cancel',
    current_password: 'Current Password',
    enter_current_password: 'Enter current password',
    new_password: 'New Password',
    enter_new_password: 'Enter new password',
    confirm_new_password: 'Confirm New Password',
    confirm_new_password_placeholder: 'Confirm new password',
    address_saved: 'Address saved successfully',
    password_changed: 'Password changed successfully',
    current_password_incorrect: 'Current password is incorrect',
    telegram: 'Telegram',
    copy: 'COPY',
    email: 'Email',
    close: 'Close',
    total_balance: 'Total Balance',
    deposit_action: 'Deposit',
    withdraw_action: 'Withdraw',
    transaction_history: 'Transaction History',
    total_earned: 'Total Earned',
    total_deposits: 'Total Deposits',
    total_withdrawals: 'Total Withdrawals',
    referral_income: 'Referral Income',
    no_transactions: 'No transactions yet',
    error_loading: 'Error loading',
    transaction_type_deposit: 'Deposit',
    transaction_type_withdrawal: 'Withdrawal',
    transaction_type_quantification: 'Quantification',
    transaction_type_referral: 'Referral',
    transaction_type_registration_bonus: 'Registration Bonus',
    company: 'Company',
    deposit: 'Deposit',
    withdraw: 'Withdraw',
    invite: 'Invite',
    team: 'Team',
    rules: 'Rules',
    live_crypto_prices: 'Live Crypto Prices',
    updating: 'Updating...',
    loading_data: 'Loading live prices...',
    offline: 'Offline',
    cached_data: 'Cached data',
    updated: 'Updated',
    our_partners: 'Our Partners',
    notification: 'Notification',
    configured: 'Configured',
    set_address: 'Set Address',
    language_english: 'English',
    language_russian: 'Russian',
    language_chinese: 'Chinese',
    error: 'Error',
    copied: 'Copied',
    confirm_logout: 'Confirm Logout',
    logout_message: 'Are you sure you want to logout?',
    please_login: 'Please login first',
    no_signals: 'No signals available',
    processing_quantification: 'Processing...',
    profit: 'Profit',
    quantification_successful: 'Quantification successful! Profit: {profit} USDT',
    quantum_signals_available: 'quantum signals available',
    analyzing_market: 'Analyzing market conditions...',
    calculating_quantum: 'Calculating quantum probabilities...',
    executing_trades: 'Executing quantum trades...',
    quantum_complete: 'Quantum quantification complete!',
    registration_bonus_rule: 'Registration bonus $3 USDT',
    referral_bonus: 'Referral bonus level {level}',
    vip_level_upgraded: 'VIP level upgraded to {level}!',
    signals_reset_alert: 'Signals have been reset for today',
    welcome_bonus_title: 'Welcome Bonus',
    welcome_bonus_message: 'Get extra bonus on your first deposit:',
    banner_1: 'GLY Quantum Investment',
    banner_2: 'High Returns',
    banner_3: 'Secure Platform'
  },
  ru: {
    welcome: 'Добро пожаловать',
    welcome_to_gly: 'Добро пожаловать в GLY',
    username: 'Имя пользователя',
    email: 'Электронная почта',
    password: 'Пароль',
    confirm_password: 'Подтвердите пароль',
    payment_password: 'Платежный пароль',
    invite_code_required: 'Код приглашения (обязательно)',
    register: 'Зарегистрироваться',
    have_account: 'Уже есть аккаунт?',
    login_now: 'Войти сейчас!',
    validation_required: 'Все поля обязательны для заполнения',
    validation_password_match: 'Пароли не совпадают',
    validation_password_length: 'Пароль должен быть не менее 6 символов',
    validation_payment_password_length: 'Платежный пароль должен быть не менее 6 символов',
    error_username_exists: 'Имя пользователя уже существует',
    error_invalid_invite: 'Неверный код приглашения',
    server_error: 'Ошибка сервера, попробуйте снова',
    registering: 'Регистрация...',
    registration_success: 'Регистрация успешна!',
    login: 'Войти',
    no_account: 'Нет аккаунта?',
    register_now: 'Зарегистрироваться сейчас!',
    database_error: 'Ошибка базы данных',
    user_not_found: 'Пользователь не найден',
    invalid_credentials: 'Неверные учетные данные',
    login_error: 'Ошибка входа',
    login_success: 'Вход выполнен успешно!',
    loading: 'Загрузка...',
    auto_quantification: 'АВТО КВАНТИФИКАЦИЯ',
    vip_levels: 'VIP Уровни',
    vip_description_1: 'VIP 1: Базовый уровень с 2.2% ежедневной доходностью',
    vip_description_2: 'VIP 2: 2.8% ежедневной доходности',
    vip_description_3: 'VIP 3: 3.5% ежедневной доходности',
    vip_description_4: 'VIP 4: 4.0% ежедневной доходности',
    vip_description_5: 'VIP 5: 5.0% ежедневной доходности',
    vip_description_6: 'VIP 6: 6.0% ежедневной доходности',
    daily_percent: 'Ежедневный процент',
    deposit_range: 'Диапазон депозита',
    signals_count: 'Сигналы',
    referrals_required: 'Требуется рефералов',
    unlocked: 'Разблокировано',
    locked: 'Заблокировано',
    id: 'ID',
    copy_id: 'Скопировать ID',
    balance: 'Баланс',
    utc_calendar: 'Календарь UTC',
    settings: 'Настройки',
    withdrawal_address: 'Адрес для вывода',
    transaction_password: 'Транзакционный пароль',
    customer_service: 'Служба поддержки',
    language: 'Язык',
    change_password: 'Изменить пароль',
    logout: 'Выйти',
    set_withdrawal_address: 'Установить адрес вывода',
    select_network: 'Выберите сеть',
    usdt_wallet_address: 'Адрес кошелька USDT',
    enter_wallet_address: 'Введите адрес вашего кошелька',
    save: 'Сохранить',
    cancel: 'Отмена',
    current_password: 'Текущий пароль',
    enter_current_password: 'Введите текущий пароль',
    new_password: 'Новый пароль',
    enter_new_password: 'Введите новый пароль',
    confirm_new_password: 'Подтвердите новый пароль',
    confirm_new_password_placeholder: 'Подтвердите новый пароль',
    address_saved: 'Адрес успешно сохранен',
    password_changed: 'Пароль успешно изменен',
    current_password_incorrect: 'Текущий пароль неверен',
    telegram: 'Telegram',
    copy: 'КОПИРОВАТЬ',
    email: 'Электронная почта',
    close: 'Закрыть',
    total_balance: 'Общий баланс',
    deposit_action: 'Депозит',
    withdraw_action: 'Вывод',
    transaction_history: 'История транзакций',
    total_earned: 'Всего заработано',
    total_deposits: 'Всего депозитов',
    total_withdrawals: 'Всего выводов',
    referral_income: 'Реферальный доход',
    no_transactions: 'Пока нет транзакций',
    error_loading: 'Ошибка загрузки',
    transaction_type_deposit: 'Депозит',
    transaction_type_withdrawal: 'Вывод',
    transaction_type_quantification: 'Квантфикация',
    transaction_type_referral: 'Реферал',
    transaction_type_registration_bonus: 'Бонус за регистрацию',
    company: 'Компания',
    deposit: 'Депозит',
    withdraw: 'Вывод',
    invite: 'Пригласить',
    team: 'Команда',
    rules: 'Правила',
    live_crypto_prices: 'Курсы криптовалют в реальном времени',
    updating: 'Обновление...',
    loading_data: 'Загрузка курсов...',
    offline: 'Офлайн',
    cached_data: 'Кэшированные данные',
    updated: 'Обновлено',
    our_partners: 'Наши партнеры',
    notification: 'Уведомление',
    configured: 'Настроено',
    set_address: 'Установить адрес',
    language_english: 'Английский',
    language_russian: 'Русский',
    language_chinese: 'Китайский',
    error: 'Ошибка',
    copied: 'Скопировано',
    confirm_logout: 'Подтвердите выход',
    logout_message: 'Вы уверены, что хотите выйти?',
    please_login: 'Пожалуйста, войдите в систему',
    no_signals: 'Нет доступных сигналов',
    processing_quantification: 'Обработка...',
    profit: 'Прибыль',
    quantification_successful: 'Квантфикация успешна! Прибыль: {profit} USDT',
    quantum_signals_available: 'квантовых сигналов доступно',
    analyzing_market: 'Анализ рыночных условий...',
    calculating_quantum: 'Расчет квантовых вероятностей...',
    executing_trades: 'Выполнение квантовых сделок...',
    quantum_complete: 'Квантовая квантфикация завершена!',
    registration_bonus_rule: 'Бонус за регистрацию $3 USDT',
    referral_bonus: 'Реферальный бонус уровень {level}',
    vip_level_upgraded: 'VIP уровень повышен до {level}!',
    signals_reset_alert: 'Сигналы сброшены на сегодня',
    welcome_bonus_title: 'Приветственный бонус',
    welcome_bonus_message: 'Получите дополнительный бонус за первый депозит:',
    banner_1: 'GLY Квантовые Инвестиции',
    banner_2: 'Высокая доходность',
    banner_3: 'Безопасная платформа'
  }
}

let currentLang = localStorage.getItem('gly_language') || 'en'

export function t(key, lang = null, params = {}) {
  const language = lang || currentLang
  let text = translations[language]?.[key] || translations['en'][key] || key
  
  // Заменяем параметры
  Object.keys(params).forEach(param => {
    text = text.replace(`{${param}}`, params[param])
  })
  
  return text
}

export function setLanguage(lang) {
  if (translations[lang]) {
    currentLang = lang
    localStorage.setItem('gly_language', lang)
    return true
  }
  return false
}

export function getCurrentLanguage() {
  return currentLang
}

export function initTranslate() {
  return {
    t,
    setLanguage,
    getCurrentLanguage,
    languages: Object.keys(translations)
  }
}
